remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Rossember Andrey Restrepo Alvarez
submodulo: Introduccion a la programacion
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/rossember-3af5f.appspot.com/o/IMG_20220830_085650.jpg?alt=media&token=a0e38232-40b1-4647-ac3a-aa48896bc3b6

